version: "2.1"

services:

  web:
    tty: true
    image: python:3.9
    depends_on:
      - db
    volumes:
      - .:/opt/kisihisi
    container_name: kisihisi-web
    ports:
      - "0.0.0.0:8080:8000"
    env_file: .env
    working_dir: /opt/kisihisi
    command: python3 src/manage.py runserver 

  bot:
    tty: true
    image: python:3.8
    depends_on:
      - db
    env_file: .env
    volumes:
      - .:/opt/kisihisi
    container_name: kisihisi-bot
    working_dir: /opt/kisihisi
    command: python3 /src/bot/bot.py

  db:
    image: postgres:12.0-alpine
    volumes:
      - ./postgres_data:/var/lib/postgresql/data
    container_name: kisihisi-db
    env_file: .env

volumes:
  postgres_data:
