# Generated by Django 3.2.4 on 2021-06-25 16:34

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('apps', '0001_initial'),
    ]

    operations = [
        migrations.AlterField(
            model_name='complex',
            name='title',
            field=models.CharField(default='', max_length=100),
        ),
        migrations.AlterField(
            model_name='procedures',
            name='title',
            field=models.CharField(default='', max_length=100),
        ),
    ]
